//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loukupm.Langue {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("loukupm.Langue.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herzlich Willkommen bei.
        /// </summary>
        internal static string aboutaswelcom {
            get {
                return ResourceManager.GetString("aboutaswelcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über uns.
        /// </summary>
        internal static string aboutusga {
            get {
                return ResourceManager.GetString("aboutusga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treffen Sie unser Team.
        /// </summary>
        internal static string AboutUsTeam {
            get {
                return ResourceManager.GetString("AboutUsTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romy Stadler.
        /// </summary>
        internal static string AboutUSTeam3 {
            get {
                return ResourceManager.GetString("AboutUSTeam3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jacqueline Oberhofer.
        /// </summary>
        internal static string AbutUSTeam2 {
            get {
                return ResourceManager.GetString("AbutUSTeam2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Passwort wurde erfolgreich zurückgesetzt..
        /// </summary>
        internal static string AcsepPassword {
            get {
                return ResourceManager.GetString("AcsepPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Passwort bestätigen.
        /// </summary>
        internal static string AcspetNewpassword {
            get {
                return ResourceManager.GetString("AcspetNewpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiter.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karte hinzufügen.
        /// </summary>
        internal static string addcard {
            get {
                return ResourceManager.GetString("addcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine weitere Dienstleistung hinzufüge.
        /// </summary>
        internal static string addservies {
            get {
                return ResourceManager.GetString("addservies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Services.
        /// </summary>
        internal static string AllServies {
            get {
                return ResourceManager.GetString("AllServies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte füllen Sie alle Felder aus.
        /// </summary>
        internal static string Alltext {
            get {
                return ResourceManager.GetString("Alltext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über die App.
        /// </summary>
        internal static string AppInfo {
            get {
                return ResourceManager.GetString("AppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benachrichtigungen.
        /// </summary>
        internal static string Benachrichtigungen {
            get {
                return ResourceManager.GetString("Benachrichtigungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin buchen.
        /// </summary>
        internal static string Booking {
            get {
                return ResourceManager.GetString("Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jetzt buchen.
        /// </summary>
        internal static string bookingNow {
            get {
                return ResourceManager.GetString("bookingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Buchung wurde erfolgreich gesendet.
        /// </summary>
        internal static string bookingsentsuccessfully {
            get {
                return ResourceManager.GetString("bookingsentsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einen Termin buchen.
        /// </summary>
        internal static string bookinNowAbotus {
            get {
                return ResourceManager.GetString("bookinNowAbotus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gültig bis.
        /// </summary>
        internal static string cardsaleh {
            get {
                return ResourceManager.GetString("cardsaleh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändern Sie das Bild.
        /// </summary>
        internal static string ChangeImage {
            get {
                return ResourceManager.GetString("ChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuelles Passwort.
        /// </summary>
        internal static string ChangMyPassword1 {
            get {
                return ResourceManager.GetString("ChangMyPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort ändern.
        /// </summary>
        internal static string ChangPassord {
            get {
                return ResourceManager.GetString("ChangPassord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort zurücksetzen.
        /// </summary>
        internal static string changvaldechen {
            get {
                return ResourceManager.GetString("changvaldechen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Dienstleistung auswählen.
        /// </summary>
        internal static string chosesservies {
            get {
                return ResourceManager.GetString("chosesservies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Dienst wurde erfolgreich hinzugefügt..
        /// </summary>
        internal static string CompletedAddServies {
            get {
                return ResourceManager.GetString("CompletedAddServies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie sind angemeldet.
        /// </summary>
        internal static string CompletedLogin {
            get {
                return ResourceManager.GetString("CompletedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Benutzerdaten wurden erfolgreich aktualisiert..
        /// </summary>
        internal static string ConfermUpateChane {
            get {
                return ResourceManager.GetString("ConfermUpateChane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password bestätigen.
        /// </summary>
        internal static string ConifermPassword {
            get {
                return ResourceManager.GetString("ConifermPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noch kein Konto?.
        /// </summary>
        internal static string CreatAccount {
            get {
                return ResourceManager.GetString("CreatAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrieren.
        /// </summary>
        internal static string CreatAcount2 {
            get {
                return ResourceManager.GetString("CreatAcount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verfügbare Zeiten an diesem Tag.
        /// </summary>
        internal static string datebooking {
            get {
                return ResourceManager.GetString("datebooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verfügbare Zeiten an diesem Bei LOOK UP Friseur in Landshut bieten wir Ihnen einen exklusiven Haarschnitt- und Styling-Service, der genau auf Ihre individuellen Wünsche und Bedürfnisse abgestimmt ist. Unsere erfahrenen Friseure verwenden die neuesten Techniken und hochwertige Produkte, um sicherzustellen, dass Sie bei jedem Besuch das bestmögliche Ergebnis erzielenTag.
        /// </summary>
        internal static string DescriptionAboutus {
            get {
                return ResourceManager.GetString("DescriptionAboutus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zum Auswählen klicken.
        /// </summary>
        internal static string descrtiondate {
            get {
                return ResourceManager.GetString("descrtiondate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie erhalten in Kürze eine E-Mail mit einem Code, um ein neues Passwort einzurichten..
        /// </summary>
        internal static string desRestPass {
            get {
                return ResourceManager.GetString("desRestPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei LOOK UP Friseur in Landshut bieten wir Ihnen einen exklusiven Haarschnitt- und Styling-Service, der genau auf Ihre individuellen Wünsche und Bedürfnisse abgestimmt ist. Unsere erfahrenen Friseure verwenden die neuesten Techniken und hochwertige Produkte, um sicherzustellen, dass Sie bei jedem Besuch das bestmögliche Ergebnis erzielen...
        /// </summary>
        internal static string DesStartPage {
            get {
                return ResourceManager.GetString("DesStartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsere Top-Stylisten sind darauf spezialisiert, individuelle Schönheit hervorzuheben und bieten professionelle Haarschnitte, Stylings und Färbungen .
        /// </summary>
        internal static string DesTeam1 {
            get {
                return ResourceManager.GetString("DesTeam1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Künstlerin mit leichter Hand und besonderer Sensibilität.
        /// </summary>
        internal static string DesTeam2 {
            get {
                return ResourceManager.GetString("DesTeam2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontodaten bKünstlerin im Damenbereich mit leichter Hand und besonderem Feingefühlearbeiten.
        /// </summary>
        internal static string DesTeam3 {
            get {
                return ResourceManager.GetString("DesTeam3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontodaten bearbeiten.
        /// </summary>
        internal static string detailesMyAccount {
            get {
                return ResourceManager.GetString("detailesMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie Ihre E-Mail-Adresse und Ihr Passwort ein..
        /// </summary>
        internal static string EnterEmailOrPassword {
            get {
                return ResourceManager.GetString("EnterEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        internal static string EROR {
            get {
                return ResourceManager.GetString("EROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommunikationsfehler.
        /// </summary>
        internal static string EroreConacted {
            get {
                return ResourceManager.GetString("EroreConacted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingabefehler.
        /// </summary>
        internal static string EroreInput {
            get {
                return ResourceManager.GetString("EroreInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie eine gültige E-Mail-Adresse ein..
        /// </summary>
        internal static string ErorEmailInput {
            get {
                return ResourceManager.GetString("ErorEmailInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldefehler.
        /// </summary>
        internal static string ErorlogIn {
            get {
                return ResourceManager.GetString("ErorlogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit Google fortfahren.
        /// </summary>
        internal static string GoogleLogin {
            get {
                return ResourceManager.GetString("GoogleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum wählen.
        /// </summary>
        internal static string historey {
            get {
                return ResourceManager.GetString("historey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie den Friseur.
        /// </summary>
        internal static string hrearchooes {
            get {
                return ResourceManager.GetString("hrearchooes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamt.
        /// </summary>
        internal static string invoic {
            get {
                return ResourceManager.GetString("invoic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link senden.
        /// </summary>
        internal static string linkpass {
            get {
                return ResourceManager.GetString("linkpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass Sie sich abmelden möchten?.
        /// </summary>
        internal static string Logoutmessag {
            get {
                return ResourceManager.GetString("Logoutmessag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Termine.
        /// </summary>
        internal static string Mybook {
            get {
                return ResourceManager.GetString("Mybook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameUser {
            get {
                return ResourceManager.GetString("NameUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Passwort.
        /// </summary>
        internal static string NewMyPassord {
            get {
                return ResourceManager.GetString("NewMyPassord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Fehler aufgetreten; die Daten wurden nicht aktualisiert. Bitte versuchen Sie es erneut..
        /// </summary>
        internal static string NoConfermChangeDataUser {
            get {
                return ResourceManager.GetString("NoConfermChangeDataUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es besteht keine Internetverbindung. Bitte überprüfen Sie Ihre Verbindung und versuchen Sie es erneut..
        /// </summary>
        internal static string NoEnternetConctesd {
            get {
                return ResourceManager.GetString("NoEnternetConctesd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde keine Antwort vom Server erhalten.
        /// </summary>
        internal static string noresponseserver {
            get {
                return ResourceManager.GetString("noresponseserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falsche E-Mail oder falsches Passwort.
        /// </summary>
        internal static string NOTEqlalepor {
            get {
                return ResourceManager.GetString("NOTEqlalepor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort vergessen?.
        /// </summary>
        internal static string NPasswordOnLogin {
            get {
                return ResourceManager.GetString("NPasswordOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kartennummer.
        /// </summary>
        internal static string nubercrad {
            get {
                return ResourceManager.GetString("nubercrad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Passwort muss mehr als 6 Zeichen enthalten.
        /// </summary>
        internal static string pasl {
            get {
                return ResourceManager.GetString("pasl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Passwörter stimmen nicht überein.
        /// </summary>
        internal static string Passwordnotmatch {
            get {
                return ResourceManager.GetString("Passwordnotmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlungsmethode.
        /// </summary>
        internal static string paymentgetwaymethod {
            get {
                return ResourceManager.GetString("paymentgetwaymethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jetzt bezahlen.
        /// </summary>
        internal static string paynaw {
            get {
                return ResourceManager.GetString("paynaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karteninhaber.
        /// </summary>
        internal static string pesoncard {
            get {
                return ResourceManager.GetString("pesoncard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonnummer.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wählen Sie mindestens einen Dienst aus, bevor Sie fortfahren..
        /// </summary>
        internal static string pleaseselectoneservice {
            get {
                return ResourceManager.GetString("pleaseselectoneservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie das Konto wirklich löschen?.
        /// </summary>
        internal static string RemoveMyCount {
            get {
                return ResourceManager.GetString("RemoveMyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie Ihre E-Mail-Adresse ein, um Anweisungen zum Zurücksetzen Ihres Passworts zu erhaltenn.
        /// </summary>
        internal static string ResetPasswordvv {
            get {
                return ResourceManager.GetString("ResetPasswordvv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderungen speichern.
        /// </summary>
        internal static string SaveChangFoeMyAccount {
            get {
                return ResourceManager.GetString("SaveChangFoeMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code wurde gesendet.
        /// </summary>
        internal static string sendotp {
            get {
                return ResourceManager.GetString("sendotp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App-Einstellungen.
        /// </summary>
        internal static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrieren.
        /// </summary>
        internal static string Singin {
            get {
                return ResourceManager.GetString("Singin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertig.
        /// </summary>
        internal static string standpay {
            get {
                return ResourceManager.GetString("standpay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasradin Albarho.
        /// </summary>
        internal static string TeamNaser {
            get {
                return ResourceManager.GetString("TeamNaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzername bereits vergeben.
        /// </summary>
        internal static string TheEmailisUSED {
            get {
                return ResourceManager.GetString("TheEmailisUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Dienst wurde bereits hinzugefügt.
        /// </summary>
        internal static string theserviewasdone {
            get {
                return ResourceManager.GetString("theserviewasdone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treffen Sie unser Team.
        /// </summary>
        internal static string TitelTeam {
            get {
                return ResourceManager.GetString("TitelTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfahrene Stylisten mit Leidenschaft und Kreativität für Ihr persönliches Styling..
        /// </summary>
        internal static string Titledescrption {
            get {
                return ResourceManager.GetString("Titledescrption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mein Profil.
        /// </summary>
        internal static string TitlwMyPrefile {
            get {
                return ResourceManager.GetString("TitlwMyPrefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinkommen - Drankommen! Besuchen Sie uns einfach spontan - auch ohne Termin!.
        /// </summary>
        internal static string VisteInAboutUS {
            get {
                return ResourceManager.GetString("VisteInAboutUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen.
        /// </summary>
        internal static string Wellcom {
            get {
                return ResourceManager.GetString("Wellcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abmelden.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haben Sie schon ein Konto?.
        /// </summary>
        internal static string YouHaveAcount {
            get {
                return ResourceManager.GetString("YouHaveAcount", resourceCulture);
            }
        }
    }
}
