//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loukupm.Langue {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("loukupm.Langue.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herzlich Willkommen bei.
        /// </summary>
        internal static string aboutaswelcom {
            get {
                return ResourceManager.GetString("aboutaswelcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über uns.
        /// </summary>
        internal static string aboutusga {
            get {
                return ResourceManager.GetString("aboutusga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treffen Sie unser Team.
        /// </summary>
        internal static string AboutUsTeam {
            get {
                return ResourceManager.GetString("AboutUsTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romy Stadler.
        /// </summary>
        internal static string AboutUSTeam3 {
            get {
                return ResourceManager.GetString("AboutUSTeam3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jacqueline Oberhofer.
        /// </summary>
        internal static string AbutUSTeam2 {
            get {
                return ResourceManager.GetString("AbutUSTeam2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Passwort wurde erfolgreich zurückgesetzt..
        /// </summary>
        internal static string AcsepPassword {
            get {
                return ResourceManager.GetString("AcsepPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Passwort bestätigen.
        /// </summary>
        internal static string AcspetNewpassword {
            get {
                return ResourceManager.GetString("AcspetNewpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiter.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karte hinzufügen.
        /// </summary>
        internal static string addcard {
            get {
                return ResourceManager.GetString("addcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine weitere Dienstleistung hinzufüge.
        /// </summary>
        internal static string addservies {
            get {
                return ResourceManager.GetString("addservies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Services.
        /// </summary>
        internal static string AllServies {
            get {
                return ResourceManager.GetString("AllServies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte füllen Sie alle Felder aus.
        /// </summary>
        internal static string Alltext {
            get {
                return ResourceManager.GetString("Alltext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to und.
        /// </summary>
        internal static string AND {
            get {
                return ResourceManager.GetString("AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über die App.
        /// </summary>
        internal static string AppInfo {
            get {
                return ResourceManager.GetString("AppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benachrichtigungen.
        /// </summary>
        internal static string Benachrichtigungen {
            get {
                return ResourceManager.GetString("Benachrichtigungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin buchen.
        /// </summary>
        internal static string Booking {
            get {
                return ResourceManager.GetString("Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jetzt buchen.
        /// </summary>
        internal static string bookingNow {
            get {
                return ResourceManager.GetString("bookingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Buchung wurde erfolgreich gesendet.
        /// </summary>
        internal static string bookingsentsuccessfully {
            get {
                return ResourceManager.GetString("bookingsentsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einen Termin buchen.
        /// </summary>
        internal static string bookinNowAbotus {
            get {
                return ResourceManager.GetString("bookinNowAbotus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gültig bis.
        /// </summary>
        internal static string cardsaleh {
            get {
                return ResourceManager.GetString("cardsaleh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Service wurde erfolgreich hinzugefügt..
        /// </summary>
        internal static string celectedserviesiddone {
            get {
                return ResourceManager.GetString("celectedserviesiddone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändern Sie das Bild.
        /// </summary>
        internal static string ChangeImage {
            get {
                return ResourceManager.GetString("ChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuelles Passwort.
        /// </summary>
        internal static string ChangMyPassword1 {
            get {
                return ResourceManager.GetString("ChangMyPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort ändern.
        /// </summary>
        internal static string ChangPassord {
            get {
                return ResourceManager.GetString("ChangPassord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort zurücksetzen.
        /// </summary>
        internal static string changvaldechen {
            get {
                return ResourceManager.GetString("changvaldechen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Dienstleistung auswählen.
        /// </summary>
        internal static string chosesservies {
            get {
                return ResourceManager.GetString("chosesservies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Code ist ungültig. Bitte versuchen Sie es erneut.
        /// </summary>
        internal static string CodeNotIncorrect {
            get {
                return ResourceManager.GetString("CodeNotIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Dienst wurde erfolgreich hinzugefügt..
        /// </summary>
        internal static string CompletedAddServies {
            get {
                return ResourceManager.GetString("CompletedAddServies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie sind angemeldet.
        /// </summary>
        internal static string CompletedLogin {
            get {
                return ResourceManager.GetString("CompletedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Bestätigungscode wurde an Ihre E-Mail-Adresse gesendet.
        /// </summary>
        internal static string CompletedSendEmaileSucsees {
            get {
                return ResourceManager.GetString("CompletedSendEmaileSucsees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Benutzerdaten wurden erfolgreich aktualisiert..
        /// </summary>
        internal static string ConfermUpateChane {
            get {
                return ResourceManager.GetString("ConfermUpateChane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password bestätigen.
        /// </summary>
        internal static string ConifermPassword {
            get {
                return ResourceManager.GetString("ConifermPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noch kein Konto?.
        /// </summary>
        internal static string CreatAccount {
            get {
                return ResourceManager.GetString("CreatAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrieren.
        /// </summary>
        internal static string CreatAcount2 {
            get {
                return ResourceManager.GetString("CreatAcount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verfügbare Zeiten an diesem Tag.
        /// </summary>
        internal static string datebooking {
            get {
                return ResourceManager.GetString("datebooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verfügbare Zeiten an diesem Bei LOOK UP Friseur in Landshut bieten wir Ihnen einen exklusiven Haarschnitt- und Styling-Service, der genau auf Ihre individuellen Wünsche und Bedürfnisse abgestimmt ist. Unsere erfahrenen Friseure verwenden die neuesten Techniken und hochwertige Produkte, um sicherzustellen, dass Sie bei jedem Besuch das bestmögliche Ergebnis erzielenTag.
        /// </summary>
        internal static string DescriptionAboutus {
            get {
                return ResourceManager.GetString("DescriptionAboutus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zum Auswählen klicken.
        /// </summary>
        internal static string descrtiondate {
            get {
                return ResourceManager.GetString("descrtiondate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie erhalten in Kürze eine E-Mail mit einem Code, um ein neues Passwort einzurichten..
        /// </summary>
        internal static string desRestPass {
            get {
                return ResourceManager.GetString("desRestPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei LOOK UP Friseur in Landshut bieten wir Ihnen einen exklusiven Haarschnitt- und Styling-Service, der genau auf Ihre individuellen Wünsche und Bedürfnisse abgestimmt ist. Unsere erfahrenen Friseure verwenden die neuesten Techniken und hochwertige Produkte, um sicherzustellen, dass Sie bei jedem Besuch das bestmögliche Ergebnis erzielen...
        /// </summary>
        internal static string DesStartPage {
            get {
                return ResourceManager.GetString("DesStartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsere Top-Stylisten sind darauf spezialisiert, individuelle Schönheit hervorzuheben und bieten professionelle Haarschnitte, Stylings und Färbungen .
        /// </summary>
        internal static string DesTeam1 {
            get {
                return ResourceManager.GetString("DesTeam1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Künstlerin mit leichter Hand und besonderer Sensibilität.
        /// </summary>
        internal static string DesTeam2 {
            get {
                return ResourceManager.GetString("DesTeam2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontodaten bKünstlerin im Damenbereich mit leichter Hand und besonderem Feingefühlearbeiten.
        /// </summary>
        internal static string DesTeam3 {
            get {
                return ResourceManager.GetString("DesTeam3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontodaten bearbeiten.
        /// </summary>
        internal static string detailesMyAccount {
            get {
                return ResourceManager.GetString("detailesMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie Ihre E-Mail-Adresse und Ihr Passwort ein..
        /// </summary>
        internal static string EnterEmailOrPassword {
            get {
                return ResourceManager.GetString("EnterEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        internal static string EROR {
            get {
                return ResourceManager.GetString("EROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Fehler während des Vorgangs aufgetreten..
        /// </summary>
        internal static string ErorDeletAccount {
            get {
                return ResourceManager.GetString("ErorDeletAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommunikationsfehler.
        /// </summary>
        internal static string EroreConacted {
            get {
                return ResourceManager.GetString("EroreConacted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingabefehler.
        /// </summary>
        internal static string EroreInput {
            get {
                return ResourceManager.GetString("EroreInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie eine gültige E-Mail-Adresse ein..
        /// </summary>
        internal static string ErorEmailInput {
            get {
                return ResourceManager.GetString("ErorEmailInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldefehler.
        /// </summary>
        internal static string ErorlogIn {
            get {
                return ResourceManager.GetString("ErorlogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Aktualisieren des Passworts ist fehlgeschlagen.
        /// </summary>
        internal static string FeildUpdatePassord {
            get {
                return ResourceManager.GetString("FeildUpdatePassord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit Google fortfahren.
        /// </summary>
        internal static string GoogleLogin {
            get {
                return ResourceManager.GetString("GoogleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum wählen.
        /// </summary>
        internal static string historey {
            get {
                return ResourceManager.GetString("historey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie den Friseur.
        /// </summary>
        internal static string hrearchooes {
            get {
                return ResourceManager.GetString("hrearchooes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Einführung.
        /// </summary>
        internal static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamt.
        /// </summary>
        internal static string invoic {
            get {
                return ResourceManager.GetString("invoic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die E-Mail-Adresse ist im System nicht registriert..
        /// </summary>
        internal static string IsYourEmailNotREGSTER {
            get {
                return ResourceManager.GetString("IsYourEmailNotREGSTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link senden.
        /// </summary>
        internal static string linkpass {
            get {
                return ResourceManager.GetString("linkpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass Sie sich abmelden möchten?.
        /// </summary>
        internal static string Logoutmessag {
            get {
                return ResourceManager.GetString("Logoutmessag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Termine.
        /// </summary>
        internal static string Mybook {
            get {
                return ResourceManager.GetString("Mybook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameUser {
            get {
                return ResourceManager.GetString("NameUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Passwort.
        /// </summary>
        internal static string NewMyPassord {
            get {
                return ResourceManager.GetString("NewMyPassord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Fehler aufgetreten; die Daten wurden nicht aktualisiert. Bitte versuchen Sie es erneut..
        /// </summary>
        internal static string NoConfermChangeDataUser {
            get {
                return ResourceManager.GetString("NoConfermChangeDataUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es besteht keine Internetverbindung. Bitte überprüfen Sie Ihre Verbindung und versuchen Sie es erneut..
        /// </summary>
        internal static string NoEnternetConctesd {
            get {
                return ResourceManager.GetString("NoEnternetConctesd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde keine Antwort vom Server erhalten.
        /// </summary>
        internal static string noresponseserver {
            get {
                return ResourceManager.GetString("noresponseserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falsche E-Mail oder falsches Passwort.
        /// </summary>
        internal static string NOTEqlalepor {
            get {
                return ResourceManager.GetString("NOTEqlalepor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Buchungen vorhanden.
        /// </summary>
        internal static string notfoundapement {
            get {
                return ResourceManager.GetString("notfoundapement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine verfügbaren Zeiten.
        /// </summary>
        internal static string notfoundtime {
            get {
                return ResourceManager.GetString("notfoundtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort vergessen?.
        /// </summary>
        internal static string NPasswordOnLogin {
            get {
                return ResourceManager.GetString("NPasswordOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kartennummer.
        /// </summary>
        internal static string nubercrad {
            get {
                return ResourceManager.GetString("nubercrad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Passwort muss mehr als 6 Zeichen enthalten.
        /// </summary>
        internal static string pasl {
            get {
                return ResourceManager.GetString("pasl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Passwörter stimmen nicht überein.
        /// </summary>
        internal static string Passwordnotmatch {
            get {
                return ResourceManager.GetString("Passwordnotmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Passwort wurde erfolgreich aktualisiert.
        /// </summary>
        internal static string PasswordUpdated {
            get {
                return ResourceManager.GetString("PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlungsmethode.
        /// </summary>
        internal static string paymentgetwaymethod {
            get {
                return ResourceManager.GetString("paymentgetwaymethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jetzt bezahlen.
        /// </summary>
        internal static string paynaw {
            get {
                return ResourceManager.GetString("paynaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karteninhaber.
        /// </summary>
        internal static string pesoncard {
            get {
                return ResourceManager.GetString("pesoncard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonnummer.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wählen Sie mindestens einen Dienst aus, bevor Sie fortfahren..
        /// </summary>
        internal static string pleaseselectoneservice {
            get {
                return ResourceManager.GetString("pleaseselectoneservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. Kontolöschung.
        /// </summary>
        internal static string PolicyAccountDeletion {
            get {
                return ResourceManager.GetString("PolicyAccountDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Benutzerdaten werden gelöscht.
        /// </summary>
        internal static string PolicyAccountDeletionData {
            get {
                return ResourceManager.GetString("PolicyAccountDeletionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzer kann sein Konto jederzeit innerhalb der App löschen über:.
        /// </summary>
        internal static string PolicyAccountDeletionDesc {
            get {
                return ResourceManager.GetString("PolicyAccountDeletionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Kontoinformationen werden gelöscht.
        /// </summary>
        internal static string PolicyAccountDeletionInfo {
            get {
                return ResourceManager.GetString("PolicyAccountDeletionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Einige Daten können aus rechtlichen Gründen für einen begrenzten Zeitraum beibehalten werden.
        /// </summary>
        internal static string PolicyAccountDeletionLegal {
            get {
                return ResourceManager.GetString("PolicyAccountDeletionLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil → Konto löschen.
        /// </summary>
        internal static string PolicyAccountDeletionPath {
            get {
                return ResourceManager.GetString("PolicyAccountDeletionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei Kontolöschung:.
        /// </summary>
        internal static string PolicyAccountDeletionWhenDelete {
            get {
                return ResourceManager.GetString("PolicyAccountDeletionWhenDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontoinformationen.
        /// </summary>
        internal static string PolicyAccountInfo {
            get {
                return ResourceManager.GetString("PolicyAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Erstellen eines Kontos in der App können wir Folgendes erfassen:.
        /// </summary>
        internal static string PolicyAccountInfoDesc {
            get {
                return ResourceManager.GetString("PolicyAccountInfoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. Kontowiederherstellung.
        /// </summary>
        internal static string PolicyAccountRecovery {
            get {
                return ResourceManager.GetString("PolicyAccountRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzer kann Zugriff auf sein Konto mit Hilfe von:.
        /// </summary>
        internal static string PolicyAccountRecoveryDesc {
            get {
                return ResourceManager.GetString("PolicyAccountRecoveryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP-Verifikationscode per E-Mail.
        /// </summary>
        internal static string PolicyAccountRecoveryOTP {
            get {
                return ResourceManager.GetString("PolicyAccountRecoveryOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenschutzrichtlinie.
        /// </summary>
        internal static string PolicyandPrivacy {
            get {
                return ResourceManager.GetString("PolicyandPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Buchungsdatum.
        /// </summary>
        internal static string PolicyBookingDate {
            get {
                return ResourceManager.GetString("PolicyBookingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buchungsinformationen.
        /// </summary>
        internal static string PolicyBookingInfo {
            get {
                return ResourceManager.GetString("PolicyBookingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei der Nutzung des Buchungsdienstes werden die folgenden Informationen gespeichert:.
        /// </summary>
        internal static string PolicyBookingInfoDesc {
            get {
                return ResourceManager.GetString("PolicyBookingInfoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Informationen werden nur zur Verwaltung von Terminen verwendet..
        /// </summary>
        internal static string PolicyBookingInfoUsage {
            get {
                return ResourceManager.GetString("PolicyBookingInfoUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Buchungszeit.
        /// </summary>
        internal static string PolicyBookingTime {
            get {
                return ResourceManager.GetString("PolicyBookingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10. Kinder.
        /// </summary>
        internal static string PolicyChildren {
            get {
                return ResourceManager.GetString("PolicyChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese App ist nicht für Kinder unter 13 Jahren bestimmt und wir erfassen absichtlich keine Kindererdaten..
        /// </summary>
        internal static string PolicyChildrenDesc {
            get {
                return ResourceManager.GetString("PolicyChildrenDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail: support@example.com.
        /// </summary>
        internal static string PolicyContactEmail {
            get {
                return ResourceManager.GetString("PolicyContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13. Kontaktieren Sie uns.
        /// </summary>
        internal static string PolicyContactUs {
            get {
                return ResourceManager.GetString("PolicyContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei Fragen zur Datenschutzrichtlinie können Sie uns kontaktieren über:.
        /// </summary>
        internal static string PolicyContactUsDesc {
            get {
                return ResourceManager.GetString("PolicyContactUsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Absturzprotokolle.
        /// </summary>
        internal static string PolicyCrashLogs {
            get {
                return ResourceManager.GetString("PolicyCrashLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Erfassung von Informationen.
        /// </summary>
        internal static string PolicyDataCollection {
            get {
                return ResourceManager.GetString("PolicyDataCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Datenschutz.
        /// </summary>
        internal static string PolicyDataProtection {
            get {
                return ResourceManager.GetString("PolicyDataProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Schutz von Datenbanken.
        /// </summary>
        internal static string PolicyDataProtectionDatabase {
            get {
                return ResourceManager.GetString("PolicyDataProtectionDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wir ergreifen angemessene Sicherheitsmaßnahmen zum Schutz von Daten, wie:.
        /// </summary>
        internal static string PolicyDataProtectionDesc {
            get {
                return ResourceManager.GetString("PolicyDataProtectionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es kann jedoch nicht garantiert werden, dass Daten im Internet vollständig sicher sind..
        /// </summary>
        internal static string PolicyDataProtectionDisclaimer {
            get {
                return ResourceManager.GetString("PolicyDataProtectionDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Verwendung von verschlüsselter Kommunikation HTTPS.
        /// </summary>
        internal static string PolicyDataProtectionHTTPS {
            get {
                return ResourceManager.GetString("PolicyDataProtectionHTTPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Verschlüsselung von Passwörtern.
        /// </summary>
        internal static string PolicyDataProtectionPassword {
            get {
                return ResourceManager.GetString("PolicyDataProtectionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Datenspeicherung.
        /// </summary>
        internal static string PolicyDataRetention {
            get {
                return ResourceManager.GetString("PolicyDataRetention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wir speichern Benutzerdaten nur, solange das Konto aktiv ist oder der Dienst erbracht werden muss.
        ///
        ///Einige Daten können für einen begrenzten Zeitraum zu rechtlichen oder technischen Zwecken gespeichert werden..
        /// </summary>
        internal static string PolicyDataRetentionDesc {
            get {
                return ResourceManager.GetString("PolicyDataRetentionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Datenweitergabe.
        /// </summary>
        internal static string PolicyDataSharing {
            get {
                return ResourceManager.GetString("PolicyDataSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Einhaltung von Gesetzen oder Rechtsverfügungen.
        /// </summary>
        internal static string PolicyDataSharingCompliance {
            get {
                return ResourceManager.GetString("PolicyDataSharingCompliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Betrieb von technischen Infrastrukturdiensten (wie Server).
        /// </summary>
        internal static string PolicyDataSharingInfrastructure {
            get {
                return ResourceManager.GetString("PolicyDataSharingInfrastructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wir verkaufen oder mieten Benutzerdaten nicht an Dritte..
        /// </summary>
        internal static string PolicyDataSharingNo {
            get {
                return ResourceManager.GetString("PolicyDataSharingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informationen können nur in folgenden Fällen weitergegeben werden:.
        /// </summary>
        internal static string PolicyDataSharingOnlyWhen {
            get {
                return ResourceManager.GetString("PolicyDataSharingOnlyWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Schutz von App-Rechten.
        /// </summary>
        internal static string PolicyDataSharingProtect {
            get {
                return ResourceManager.GetString("PolicyDataSharingProtect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geräteinformationen.
        /// </summary>
        internal static string PolicyDeviceInfo {
            get {
                return ResourceManager.GetString("PolicyDeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatisch können technische Informationen wie folgt erfasst werden:.
        /// </summary>
        internal static string PolicyDeviceInfoDesc {
            get {
                return ResourceManager.GetString("PolicyDeviceInfoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Informationen werden zur Verbesserung der App-Leistung verwendet..
        /// </summary>
        internal static string PolicyDeviceInfoUsage {
            get {
                return ResourceManager.GetString("PolicyDeviceInfoUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Gerätetyp.
        /// </summary>
        internal static string PolicyDeviceType {
            get {
                return ResourceManager.GetString("PolicyDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • E-Mail-Adresse.
        /// </summary>
        internal static string PolicyEmail {
            get {
                return ResourceManager.GetString("PolicyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wir verwenden diese Informationen nur zum Erstellen des Benutzerkontos in der App..
        /// </summary>
        internal static string PolicyGoogleInfo {
            get {
                return ResourceManager.GetString("PolicyGoogleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google-Anmeldung.
        /// </summary>
        internal static string PolicyGoogleLogin {
            get {
                return ResourceManager.GetString("PolicyGoogleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn Sie sich mit einem Google-Konto anmelden, können wir Folgendes erhalten:.
        /// </summary>
        internal static string PolicyGoogleLoginDesc {
            get {
                return ResourceManager.GetString("PolicyGoogleLoginDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einführung.
        /// </summary>
        internal static string PolicyIntroduction {
            get {
                return ResourceManager.GetString("PolicyIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wir in der Friseurtermin-Buchungs-App respektieren die Privatsphäre der Benutzer und sind verpflichtet, ihre persönlichen Daten zu schützen. Diese Datenschutzrichtlinie erläutert, wie wir Informationen erfassen, verwenden und schützen, wenn Sie die App nutzen.
        ///
        ///Durch die Nutzung der App stimmen Sie den in dieser Richtlinie beschriebenen Praktiken zu..
        /// </summary>
        internal static string PolicyIntroductionText {
            get {
                return ResourceManager.GetString("PolicyIntroductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • IP-Adresse.
        /// </summary>
        internal static string PolicyIPAddress {
            get {
                return ResourceManager.GetString("PolicyIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Nachname.
        /// </summary>
        internal static string PolicyLastName {
            get {
                return ResourceManager.GetString("PolicyLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzte Aktualisierung: Dezember 2026.
        /// </summary>
        internal static string PolicyLastUpdate {
            get {
                return ResourceManager.GetString("PolicyLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Name.
        /// </summary>
        internal static string PolicyName {
            get {
                return ResourceManager.GetString("PolicyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Buchungsbestätigung.
        /// </summary>
        internal static string PolicyNotificationBookingConfirm {
            get {
                return ResourceManager.GetString("PolicyNotificationBookingConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Erinnerung an Buchungstermin.
        /// </summary>
        internal static string PolicyNotificationReminder {
            get {
                return ResourceManager.GetString("PolicyNotificationReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Benachrichtigungen.
        /// </summary>
        internal static string PolicyNotifications {
            get {
                return ResourceManager.GetString("PolicyNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die App kann Benachrichtigungen an Benutzer senden wie:.
        /// </summary>
        internal static string PolicyNotificationsDesc {
            get {
                return ResourceManager.GetString("PolicyNotificationsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzer kann Benachrichtigungen jederzeit über die Geräteeinstellungen deaktivieren..
        /// </summary>
        internal static string PolicyNotificationsDisable {
            get {
                return ResourceManager.GetString("PolicyNotificationsDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Servicebezogene Updates.
        /// </summary>
        internal static string PolicyNotificationUpdates {
            get {
                return ResourceManager.GetString("PolicyNotificationUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Betriebssystem.
        /// </summary>
        internal static string PolicyOperatingSystem {
            get {
                return ResourceManager.GetString("PolicyOperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Passwort (wird verschlüsselt gespeichert).
        /// </summary>
        internal static string PolicyPassword {
            get {
                return ResourceManager.GetString("PolicyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12. Änderungen der Datenschutzrichtlinie.
        /// </summary>
        internal static string PolicyPolicyChanges {
            get {
                return ResourceManager.GetString("PolicyPolicyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wir können diese Richtlinie von Zeit zu Zeit aktualisieren. Benutzer werden über die App über Änderungen informiert..
        /// </summary>
        internal static string PolicyPolicyChangesDesc {
            get {
                return ResourceManager.GetString("PolicyPolicyChangesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Dienstleistungsanbieter (Friseur).
        /// </summary>
        internal static string PolicyServiceProvider {
            get {
                return ResourceManager.GetString("PolicyServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Art der angeforderten Dienstleistung.
        /// </summary>
        internal static string PolicyServiceType {
            get {
                return ResourceManager.GetString("PolicyServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11. Drittanbieter-Services.
        /// </summary>
        internal static string PolicyThirdParty {
            get {
                return ResourceManager.GetString("PolicyThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die App kann externe Services wie:.
        /// </summary>
        internal static string PolicyThirdPartyDesc {
            get {
                return ResourceManager.GetString("PolicyThirdPartyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Services unterliegen möglicherweise ihren eigenen Datenschutzrichtlinien..
        /// </summary>
        internal static string PolicyThirdPartyDisclaimer {
            get {
                return ResourceManager.GetString("PolicyThirdPartyDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Google-Anmeldung.
        /// </summary>
        internal static string PolicyThirdPartyGoogle {
            get {
                return ResourceManager.GetString("PolicyThirdPartyGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Benachrichtigungsdienste.
        /// </summary>
        internal static string PolicyThirdPartyNotifications {
            get {
                return ResourceManager.GetString("PolicyThirdPartyNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Wie wir Informationen verwenden.
        /// </summary>
        internal static string PolicyUsage {
            get {
                return ResourceManager.GetString("PolicyUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Erstellen des Benutzerkontos.
        /// </summary>
        internal static string PolicyUsageCreateAccount {
            get {
                return ResourceManager.GetString("PolicyUsageCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wir verwenden die Informationen für die folgenden Zwecke:.
        /// </summary>
        internal static string PolicyUsageDesc {
            get {
                return ResourceManager.GetString("PolicyUsageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Informationen werden nicht ohne Benutzereinwilligung für andere Zwecke verwendet..
        /// </summary>
        internal static string PolicyUsageDisclaimer {
            get {
                return ResourceManager.GetString("PolicyUsageDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • App-Leistung verbessern.
        /// </summary>
        internal static string PolicyUsageImproveApp {
            get {
                return ResourceManager.GetString("PolicyUsageImproveApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Anmeldung und Kontoverwaltung.
        /// </summary>
        internal static string PolicyUsageManageAccount {
            get {
                return ResourceManager.GetString("PolicyUsageManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Buchungsverwaltung.
        /// </summary>
        internal static string PolicyUsageManageBooking {
            get {
                return ResourceManager.GetString("PolicyUsageManageBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Betrugsprävention oder Missbrauch verhindern.
        /// </summary>
        internal static string PolicyUsagePreventFraud {
            get {
                return ResourceManager.GetString("PolicyUsagePreventFraud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Senden von buchungsbezogenen Benachrichtigungen.
        /// </summary>
        internal static string PolicyUsageSendNotifications {
            get {
                return ResourceManager.GetString("PolicyUsageSendNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Benutzerunterstützung.
        /// </summary>
        internal static string PolicyUsageSupport {
            get {
                return ResourceManager.GetString("PolicyUsageSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. Benutzerrechte.
        /// </summary>
        internal static string PolicyUserRights {
            get {
                return ResourceManager.GetString("PolicyUserRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Auf seine Daten zugreifen.
        /// </summary>
        internal static string PolicyUserRightsAccess {
            get {
                return ResourceManager.GetString("PolicyUserRightsAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Sein Konto löschen.
        /// </summary>
        internal static string PolicyUserRightsDelete {
            get {
                return ResourceManager.GetString("PolicyUserRightsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzer hat das Recht:.
        /// </summary>
        internal static string PolicyUserRightsDesc {
            get {
                return ResourceManager.GetString("PolicyUserRightsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Seine Daten ändern.
        /// </summary>
        internal static string PolicyUserRightsModify {
            get {
                return ResourceManager.GetString("PolicyUserRightsModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Löschung seiner Daten anfordern.
        /// </summary>
        internal static string PolicyUserRightsRequest {
            get {
                return ResourceManager.GetString("PolicyUserRightsRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie das Konto wirklich löschen?.
        /// </summary>
        internal static string RemoveMyCount {
            get {
                return ResourceManager.GetString("RemoveMyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie Ihre E-Mail-Adresse ein, um Anweisungen zum Zurücksetzen Ihres Passworts zu erhaltenn.
        /// </summary>
        internal static string ResetPasswordvv {
            get {
                return ResourceManager.GetString("ResetPasswordvv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfolg.
        /// </summary>
        internal static string Sacsess {
            get {
                return ResourceManager.GetString("Sacsess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderungen speichern.
        /// </summary>
        internal static string SaveChangFoeMyAccount {
            get {
                return ResourceManager.GetString("SaveChangFoeMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code wurde gesendet.
        /// </summary>
        internal static string sendotp {
            get {
                return ResourceManager.GetString("sendotp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App-Einstellungen.
        /// </summary>
        internal static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrieren.
        /// </summary>
        internal static string Singin {
            get {
                return ResourceManager.GetString("Singin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertig.
        /// </summary>
        internal static string standpay {
            get {
                return ResourceManager.GetString("standpay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to „Der Code wurde erfolgreich verifiziert.
        /// </summary>
        internal static string SuccessfullyVerified {
            get {
                return ResourceManager.GetString("SuccessfullyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasradin Albarho.
        /// </summary>
        internal static string TeamNaser {
            get {
                return ResourceManager.GetString("TeamNaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasradin Albarho.
        /// </summary>
        internal static string TermsAbusiveUse {
            get {
                return ResourceManager.GetString("TermsAbusiveUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Missbrauch der Anwendung.
        /// </summary>
        internal static string TermsAccountActivities {
            get {
                return ResourceManager.GetString("TermsAccountActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Alle Aktivitäten, die über sein Konto durchgeführt werden.
        /// </summary>
        internal static string TermsAccountResponsibility {
            get {
                return ResourceManager.GetString("TermsAccountResponsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Konten.
        /// </summary>
        internal static string TermsAccounts {
            get {
                return ResourceManager.GetString("TermsAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die App-Verwaltung kann das Konto sperren oder löschen, falls:.
        /// </summary>
        internal static string TermsAccountSuspend {
            get {
                return ResourceManager.GetString("TermsAccountSuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. Kündigung des Kontos.
        /// </summary>
        internal static string TermsAccountTermination {
            get {
                return ResourceManager.GetString("TermsAccountTermination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die App-Verwaltung kann das Konto auch kündigen, wenn gegen die Bedingungen verstoßen wird..
        /// </summary>
        internal static string TermsAdminCanTerminate {
            get {
                return ResourceManager.GetString("TermsAdminCanTerminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzungsbedingungen.
        /// </summary>
        internal static string TermsandConditions {
            get {
                return ResourceManager.GetString("TermsandConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Verwendung der Anwendung.
        /// </summary>
        internal static string TermsAppUsage {
            get {
                return ResourceManager.GetString("TermsAppUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzer erklärt sich bereit:.
        /// </summary>
        internal static string TermsAppUsageAgreement {
            get {
                return ResourceManager.GetString("TermsAppUsageAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die App ist zur Buchung von Friseurterminen bestimmt..
        /// </summary>
        internal static string TermsAppUsageDesc {
            get {
                return ResourceManager.GetString("TermsAppUsageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Müssen Sie sich an die vereinbarte Zeit halten.
        /// </summary>
        internal static string TermsAttendOnTime {
            get {
                return ResourceManager.GetString("TermsAttendOnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. Verfügbarkeit der App.
        /// </summary>
        internal static string TermsAvailability {
            get {
                return ResourceManager.GetString("TermsAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wir bemühen uns, die App ständig verfügbar zu halten, können aber nicht garantieren:.
        /// </summary>
        internal static string TermsAvailabilityEffort {
            get {
                return ResourceManager.GetString("TermsAvailabilityEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei der Buchung eines Termins:.
        /// </summary>
        internal static string TermsBookingCommitment {
            get {
                return ResourceManager.GetString("TermsBookingCommitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Buchungen.
        /// </summary>
        internal static string TermsBookings {
            get {
                return ResourceManager.GetString("TermsBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzer kann einen Termin über die App vor dem vereinbarten Termin stornieren..
        /// </summary>
        internal static string TermsCancelBooking {
            get {
                return ResourceManager.GetString("TermsCancelBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Stornierung.
        /// </summary>
        internal static string TermsCancellation {
            get {
                return ResourceManager.GetString("TermsCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die App-Verwaltung kann diese Bedingungen jederzeit ändern..
        /// </summary>
        internal static string TermsCanModify {
            get {
                return ResourceManager.GetString("TermsCanModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Zahlungen erfolgen direkt in bar am Standort des Dienstleisters (Friseur)..
        /// </summary>
        internal static string TermsCashPayment {
            get {
                return ResourceManager.GetString("TermsCashPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durch die Nutzung der Friseurtermin-Buchungs-App stimmen Sie den folgenden Bedingungen zu..
        /// </summary>
        internal static string TermsIntroduction {
            get {
                return ResourceManager.GetString("TermsIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Geheimhaltung des Passworts.
        /// </summary>
        internal static string TermsKeepPassword {
            get {
                return ResourceManager.GetString("TermsKeepPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzte Aktualisierung: März 2026.
        /// </summary>
        internal static string TermsLastUpdateTerms {
            get {
                return ResourceManager.GetString("TermsLastUpdateTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Bei Verspätung kann die Buchung storniert werden.
        /// </summary>
        internal static string TermsLateCancel {
            get {
                return ResourceManager.GetString("TermsLateCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. Änderungen.
        /// </summary>
        internal static string TermsModifications {
            get {
                return ResourceManager.GetString("TermsModifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • 100%ige Servicegarantie.
        /// </summary>
        internal static string TermsNoFullGuarantee {
            get {
                return ResourceManager.GetString("TermsNoFullGuarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Keine Versuche zu unternehmen, in das System einzudringen oder es zu stören.
        /// </summary>
        internal static string TermsNoHacking {
            get {
                return ResourceManager.GetString("TermsNoHacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die App unterstützt keine Online-Zahlungen..
        /// </summary>
        internal static string TermsNoOnlinePayment {
            get {
                return ResourceManager.GetString("TermsNoOnlinePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Keine technischen Probleme.
        /// </summary>
        internal static string TermsNoTechnicalIssues {
            get {
                return ResourceManager.GetString("TermsNoTechnicalIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie trägt keine Verantwortung für:.
        /// </summary>
        internal static string TermsNotResponsible {
            get {
                return ResourceManager.GetString("TermsNotResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Zahlung.
        /// </summary>
        internal static string TermsPayment {
            get {
                return ResourceManager.GetString("TermsPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die App funktioniert nur als Terminbuchungsplattform..
        /// </summary>
        internal static string TermsPlatformOnly {
            get {
                return ResourceManager.GetString("TermsPlatformOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Korrekte Informationen bei der Registrierung zu bewahren.
        /// </summary>
        internal static string TermsProvideCorrectInfo {
            get {
                return ResourceManager.GetString("TermsProvideCorrectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Qualität der vom Dienstleister erbrachten Leistungen.
        /// </summary>
        internal static string TermsQualityOfService {
            get {
                return ResourceManager.GetString("TermsQualityOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Service-Verantwortung.
        /// </summary>
        internal static string TermsServiceResponsibility {
            get {
                return ResourceManager.GetString("TermsServiceResponsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Die App auf legale Weise zu nutzen.
        /// </summary>
        internal static string TermsUseLegalWay {
            get {
                return ResourceManager.GetString("TermsUseLegalWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Die App auf legale Weise zu nutzen.
        /// </summary>
        internal static string TermsUserCanDelete {
            get {
                return ResourceManager.GetString("TermsUserCanDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzer kann sein Konto jederzeit löschen..
        /// </summary>
        internal static string TermsUserDispute {
            get {
                return ResourceManager.GetString("TermsUserDispute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Verstoß gegen die Bedingungen.
        /// </summary>
        internal static string TermsViolateTerms {
            get {
                return ResourceManager.GetString("TermsViolateTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzername bereits vergeben.
        /// </summary>
        internal static string TheEmailisUSED {
            get {
                return ResourceManager.GetString("TheEmailisUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Dienst wurde bereits hinzugefügt.
        /// </summary>
        internal static string theserviewasdone {
            get {
                return ResourceManager.GetString("theserviewasdone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treffen Sie unser Team.
        /// </summary>
        internal static string TitelTeam {
            get {
                return ResourceManager.GetString("TitelTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfahrene Stylisten mit Leidenschaft und Kreativität für Ihr persönliches Styling..
        /// </summary>
        internal static string Titledescrption {
            get {
                return ResourceManager.GetString("Titledescrption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mein Profil.
        /// </summary>
        internal static string TitlwMyPrefile {
            get {
                return ResourceManager.GetString("TitlwMyPrefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinkommen - Drankommen! Besuchen Sie uns einfach spontan - auch ohne Termin!.
        /// </summary>
        internal static string VisteInAboutUS {
            get {
                return ResourceManager.GetString("VisteInAboutUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein OTP wurde kürzlich angefordert. Bitte warten Sie, bevor Sie es erneut versuchen..
        /// </summary>
        internal static string WateResposeOTP {
            get {
                return ResourceManager.GetString("WateResposeOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen.
        /// </summary>
        internal static string Wellcom {
            get {
                return ResourceManager.GetString("Wellcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abmelden.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haben Sie schon ein Konto?.
        /// </summary>
        internal static string YouHaveAcount {
            get {
                return ResourceManager.GetString("YouHaveAcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben bisher noch keinen Termin gebucht.
        /// </summary>
        internal static string younotapement {
            get {
                return ResourceManager.GetString("younotapement", resourceCulture);
            }
        }
    }
}
